services:
  server:
    build: .
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/firebase-service-account.json
    volumes:
      - ./secrets/firebase-service-account.json:/app/secrets/firebase-service-account.json:ro